// <auto-generated />
using EDAI.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EDAI.Server.Migrations
{
    [DbContext(typeof(EdaiContext))]
    [Migration("20241222005925_createDatabase")]
    partial class createDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("EDAI.Shared.Models.Assignment", b =>
                {
                    b.Property<int>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AssignmentId");

                    b.ToTable("Assignments");
                });

            modelBuilder.Entity("EDAI.Shared.Models.Essay", b =>
                {
                    b.Property<int>("EssayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AssignmentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ScoreId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("EssayId");

                    b.HasIndex("AssignmentId");

                    b.HasIndex("ScoreId");

                    b.HasIndex("StudentId");

                    b.ToTable("Essays");
                });

            modelBuilder.Entity("EDAI.Shared.Models.Score", b =>
                {
                    b.Property<int>("ScoreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("OverallScore")
                        .HasColumnType("REAL");

                    b.Property<float>("ScoreTheme1")
                        .HasColumnType("REAL");

                    b.Property<float>("ScoreTheme2")
                        .HasColumnType("REAL");

                    b.Property<float>("ScoreThemeN")
                        .HasColumnType("REAL");

                    b.HasKey("ScoreId");

                    b.ToTable("Scores");
                });

            modelBuilder.Entity("EDAI.Shared.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GraduationYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("StudentId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("EDAI.Shared.Models.Essay", b =>
                {
                    b.HasOne("EDAI.Shared.Models.Assignment", "Assignment")
                        .WithMany("Essays")
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EDAI.Shared.Models.Score", "Score")
                        .WithMany("Essays")
                        .HasForeignKey("ScoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EDAI.Shared.Models.Student", "Student")
                        .WithMany("Essays")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assignment");

                    b.Navigation("Score");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("EDAI.Shared.Models.Assignment", b =>
                {
                    b.Navigation("Essays");
                });

            modelBuilder.Entity("EDAI.Shared.Models.Score", b =>
                {
                    b.Navigation("Essays");
                });

            modelBuilder.Entity("EDAI.Shared.Models.Student", b =>
                {
                    b.Navigation("Essays");
                });
#pragma warning restore 612, 618
        }
    }
}
