// <auto-generated />
using System;
using EDAI.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EDAI.Server.Migrations
{
    [DbContext(typeof(EdaiContext))]
    [Migration("20250730165141_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EDAI.Shared.Models.Entities.Assignment", b =>
                {
                    b.Property<int>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AssignmentId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Open")
                        .HasColumnType("boolean");

                    b.Property<int?>("ReferenceDocumentId")
                        .HasColumnType("integer");

                    b.HasKey("AssignmentId");

                    b.HasIndex("ReferenceDocumentId");

                    b.ToTable("Assignments");
                });

            modelBuilder.Entity("EDAI.Shared.Models.Entities.EdaiDocument", b =>
                {
                    b.Property<int>("EdaiDocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EdaiDocumentId"));

                    b.Property<byte[]>("DocumentFile")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("DocumentFileExtension")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DocumentName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("EdaiDocumentId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("EDAI.Shared.Models.Entities.Essay", b =>
                {
                    b.Property<int>("EssayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EssayId"));

                    b.Property<int>("AssignmentId")
                        .HasColumnType("integer");

                    b.Property<int>("EdaiDocumentId")
                        .HasColumnType("integer");

                    b.Property<bool>("Evaluated")
                        .HasColumnType("boolean");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.HasKey("EssayId");

                    b.HasIndex("AssignmentId");

                    b.HasIndex("EdaiDocumentId");

                    b.HasIndex("StudentId");

                    b.ToTable("Essays");
                });

            modelBuilder.Entity("EDAI.Shared.Models.Entities.FeedbackComment", b =>
                {
                    b.Property<int>("FeedbackCommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FeedbackCommentId"));

                    b.Property<string>("CommentFeedback")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CommentType")
                        .HasColumnType("integer");

                    b.HasKey("FeedbackCommentId");

                    b.ToTable("FeedbackComments");
                });

            modelBuilder.Entity("EDAI.Shared.Models.Entities.IndexedContent", b =>
                {
                    b.Property<int>("IndexedContentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IndexedContentId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EssayId")
                        .HasColumnType("integer");

                    b.Property<int?>("FromCharInContent")
                        .HasColumnType("integer");

                    b.Property<int>("ParagraphIndex")
                        .HasColumnType("integer");

                    b.Property<int>("RunIndex")
                        .HasColumnType("integer");

                    b.Property<int?>("ToCharInContent")
                        .HasColumnType("integer");

                    b.HasKey("IndexedContentId");

                    b.HasIndex("EssayId");

                    b.ToTable("IndexedContents");
                });

            modelBuilder.Entity("EDAI.Shared.Models.Entities.Score", b =>
                {
                    b.Property<int>("ScoreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ScoreId"));

                    b.Property<string>("ArgumentationRecommendation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("ArgumentationScore")
                        .HasColumnType("real");

                    b.Property<string>("AssignmentAnswer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AssignmentAnswerRecommendation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("AssignmentAnswerScore")
                        .HasColumnType("real");

                    b.Property<string>("EloquenceRecommendation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("EloquenceScore")
                        .HasColumnType("real");

                    b.Property<int>("EssayId")
                        .HasColumnType("integer");

                    b.Property<int?>("EvaluatedEssayDocumentId")
                        .HasColumnType("integer");

                    b.Property<string>("GrammarRecommendation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("GrammarScore")
                        .HasColumnType("real");

                    b.Property<float>("OverallScore")
                        .HasColumnType("real");

                    b.Property<string>("OverallStructure")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OverallStructureRecommendation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("OverallStructureScore")
                        .HasColumnType("real");

                    b.HasKey("ScoreId");

                    b.HasIndex("EssayId");

                    b.HasIndex("EvaluatedEssayDocumentId");

                    b.ToTable("Scores");
                });

            modelBuilder.Entity("EDAI.Shared.Models.Entities.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StudentId"));

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("GraduationYear")
                        .HasColumnType("integer");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StudentClassId")
                        .HasColumnType("integer");

                    b.HasKey("StudentId");

                    b.HasIndex("StudentClassId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("EDAI.Shared.Models.Entities.StudentClass", b =>
                {
                    b.Property<int>("StudentClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StudentClassId"));

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("School")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("StudentClassId");

                    b.ToTable("StudentClasses");
                });

            modelBuilder.Entity("EDAI.Shared.Models.Entities.StudentSummary", b =>
                {
                    b.Property<int>("StudentSummaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StudentSummaryId"));

                    b.Property<string>("FocusArea1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FocusArea2")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FocusArea3")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("StudentSummaryId");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentSummaries");
                });

            modelBuilder.Entity("FeedbackCommentIndexedContent", b =>
                {
                    b.Property<int>("FeedbackCommentsFeedbackCommentId")
                        .HasColumnType("integer");

                    b.Property<int>("RelatedTextsIndexedContentId")
                        .HasColumnType("integer");

                    b.HasKey("FeedbackCommentsFeedbackCommentId", "RelatedTextsIndexedContentId");

                    b.HasIndex("RelatedTextsIndexedContentId");

                    b.ToTable("FeedbackCommentIndexedContent");
                });

            modelBuilder.Entity("EDAI.Shared.Models.Entities.Assignment", b =>
                {
                    b.HasOne("EDAI.Shared.Models.Entities.EdaiDocument", "ReferenceDocument")
                        .WithMany()
                        .HasForeignKey("ReferenceDocumentId");

                    b.Navigation("ReferenceDocument");
                });

            modelBuilder.Entity("EDAI.Shared.Models.Entities.Essay", b =>
                {
                    b.HasOne("EDAI.Shared.Models.Entities.Assignment", "Assignment")
                        .WithMany("Essays")
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EDAI.Shared.Models.Entities.EdaiDocument", "Document")
                        .WithMany()
                        .HasForeignKey("EdaiDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EDAI.Shared.Models.Entities.Student", "Student")
                        .WithMany("Essays")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assignment");

                    b.Navigation("Document");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("EDAI.Shared.Models.Entities.IndexedContent", b =>
                {
                    b.HasOne("EDAI.Shared.Models.Entities.Essay", "Essay")
                        .WithMany("IndexedEssay")
                        .HasForeignKey("EssayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Essay");
                });

            modelBuilder.Entity("EDAI.Shared.Models.Entities.Score", b =>
                {
                    b.HasOne("EDAI.Shared.Models.Entities.Essay", "Essay")
                        .WithMany("Scores")
                        .HasForeignKey("EssayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EDAI.Shared.Models.Entities.EdaiDocument", "EvaluatedEssayDocument")
                        .WithMany()
                        .HasForeignKey("EvaluatedEssayDocumentId");

                    b.Navigation("Essay");

                    b.Navigation("EvaluatedEssayDocument");
                });

            modelBuilder.Entity("EDAI.Shared.Models.Entities.Student", b =>
                {
                    b.HasOne("EDAI.Shared.Models.Entities.StudentClass", "StudentClass")
                        .WithMany("Students")
                        .HasForeignKey("StudentClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudentClass");
                });

            modelBuilder.Entity("EDAI.Shared.Models.Entities.StudentSummary", b =>
                {
                    b.HasOne("EDAI.Shared.Models.Entities.Student", "Student")
                        .WithMany("StudentSummaries")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("FeedbackCommentIndexedContent", b =>
                {
                    b.HasOne("EDAI.Shared.Models.Entities.FeedbackComment", null)
                        .WithMany()
                        .HasForeignKey("FeedbackCommentsFeedbackCommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EDAI.Shared.Models.Entities.IndexedContent", null)
                        .WithMany()
                        .HasForeignKey("RelatedTextsIndexedContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EDAI.Shared.Models.Entities.Assignment", b =>
                {
                    b.Navigation("Essays");
                });

            modelBuilder.Entity("EDAI.Shared.Models.Entities.Essay", b =>
                {
                    b.Navigation("IndexedEssay");

                    b.Navigation("Scores");
                });

            modelBuilder.Entity("EDAI.Shared.Models.Entities.Student", b =>
                {
                    b.Navigation("Essays");

                    b.Navigation("StudentSummaries");
                });

            modelBuilder.Entity("EDAI.Shared.Models.Entities.StudentClass", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
